name: flutter_fake_filler
description: "A Flutter package that automatically fills form fields with dummy data for development and testing purposes. Inspired by the Fake Filler browser extension."
version: 1.1.0
homepage: https://github.com/nishansr/flutter_fake_filler
repository: https://github.com/nishansr/flutter_fake_filler
issue_tracker: https://github.com/nishansr/flutter_fake_filler/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: